'use strict';

const { execSync } = require('child_process');
const path = require('path');
const fs = require('fs');

function generatePRTitle(phaseNumber, phaseName) {
  return `feat(phase-${phaseNumber}): ${phaseName}`;
}

function generatePRBody(docsRoot, phaseNumber) {
  const phaseDir = path.join(docsRoot, 'phases', String(phaseNumber));
  const lines = ['## Summary', ''];

  const summaryFiles = [];
  if (fs.existsSync(phaseDir)) {
    const files = fs.readdirSync(phaseDir).filter((f) => f.endsWith('-SUMMARY.md'));
    files.sort();
    summaryFiles.push(...files.map((f) => path.join(phaseDir, f)));
  }

  if (summaryFiles.length > 0) {
    summaryFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const titleMatch = content.match(/^#\s+(.+)/m);
      const title = titleMatch ? titleMatch[1] : path.basename(file, '.md');
      lines.push(`- ${title}`);
    });
  } else {
    lines.push('- Phase execution complete');
  }

  lines.push('', '## Verification', '');

  const verificationPath = path.join(phaseDir, `${phaseNumber}-VERIFICATION.md`);
  if (fs.existsSync(verificationPath)) {
    lines.push('- ✓ Automated verification passed');
  } else {
    lines.push('- ⚠ No verification report found');
  }

  lines.push('', '## Test Plan', '');
  lines.push('- [ ] Smoke test core functionality');
  lines.push('- [ ] Review generated code');
  lines.push('- [ ] Verify no regressions');
  lines.push('');
  lines.push('---');
  lines.push('_Generated by GTD `/gtd-ship`_');

  return lines.join('\n');
}

function getPhaseNameFromRoadmap(docsRoot, phaseNumber) {
  const roadmapPath = path.join(docsRoot, 'ROADMAP.md');
  if (!fs.existsSync(roadmapPath)) return `Phase ${phaseNumber}`;

  const content = fs.readFileSync(roadmapPath, 'utf8');
  const phaseRegex = new RegExp(
    `(?:Phase\\s*${phaseNumber}|##\\s*${phaseNumber})[:\\s—-]+(.+)`,
    'i',
  );
  const match = content.match(phaseRegex);
  return match ? match[1].trim() : `Phase ${phaseNumber}`;
}

function getCurrentBranch() {
  try {
    return execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf8' }).trim();
  } catch {
    return null;
  }
}

function hasGhCli() {
  try {
    execSync('which gh', { encoding: 'utf8' });
    return true;
  } catch {
    return false;
  }
}

module.exports = {
  generatePRTitle,
  generatePRBody,
  getPhaseNameFromRoadmap,
  getCurrentBranch,
  hasGhCli,
};
